# Build Configuration for AUTO_MAA_Go_Updater

project:
  name: "AUTO_MAA_Go_Updater"
  module: "AUTO_MAA_Go_Updater"
  description: "AUTO_MAA_Go版本更新器"

version:
  default: "1.0.0"
  build_time_format: "2006-01-02T15:04:05Z"

targets:
  - name: "windows-amd64"
    goos: "windows"
    goarch: "amd64"
    cgo_enabled: true
    output: "AUTO_MAA_Go_Updater.exe"
    
build:
  flags:
    ldflags: "-s -w"
    tags: []
    
  optimization:
    strip_debug: true
    strip_symbols: true
    upx_compression: false  # Optional, requires UPX
    
  size_requirements:
    max_size_mb: 10
    warn_size_mb: 8

assets:
  embed:
    - "assets/config_template.yaml"
  
directories:
  build: "build"
  dist: "dist"
  temp: "temp"

version_injection:
  package: "AUTO_MAA_Go_Updater/version"
  variables:
    - name: "Version"
      source: "version"
    - name: "BuildTime" 
      source: "build_time"
    - name: "GitCommit"
      source: "git_commit"

quality:
  run_tests: true
  run_lint: false  # Optional
  format_code: true